openai:
  api_key: "your key"
  base_url: ""
  model: "gpt-4o-mini"

gemini:
  model: "gemini-1.5-flash"
  base_url: ""
  api_key: "your key"

deepseek:
  model: "deepseek-r1:8b"
  base_url: "http://127.0.0.1:11434"
