deepseek:
  model: deepseek-r1:1.5b
gemini:
  api_key: AIzaSyAsmG9yGsqS08hUmpGoGzM2AH-gmdk05p8
  base_url: https://gemini.wujiafa.us.kg/v1
  model: gemini-2.0-flash-thinking-exp-1219
openai:
  api_key: sk-nsgaITlzpL32xiKcYLq1UY9SXUTzwMgAfxob0REwdCAzv9lY
  base_url: https://api.chatanywhere.tech
  model: gpt-4o-mini
reasoner:
  deepseek:
    base_url: http://127.0.0.1:11434
    model: deepseek-r1:1.5b
selected_adapter: gemini
